"""Exercises the real ffprobe/ffmpeg subprocess wrapper against a genuinely
synthetic video clip generated by ffmpeg's own `lavfi`/`testsrc` test-source
filter (see the `synthetic_clip` fixture) -- no downloaded, copyrighted, or
otherwise externally-sourced footage is involved anywhere in this project;
see PROJECT_STATUS.md for why no real volleyball video exists yet.

All tests here are skipped (not failed) when no ffmpeg/ffprobe binary is on
PATH at all, so this file doesn't break in an environment with no ffmpeg
installed. `test_installed_ffmpeg_build_is_license_clean`, when it *does*
run, asserts the real, installed ffmpeg build's own -version output has no
GPL/nonfree markers per LICENSE_DECISIONS.md D-006 -- this is deliberately
NOT mocked, because the entire point is to catch whatever build is actually
on PATH in this environment. On a host machine with an arbitrary system
ffmpeg (e.g. a GPL build installed for unrelated reasons) this test is
*expected* to fail, correctly -- see infra/scripts/install-ffmpeg-lgpl.sh
and infra/docker/python.Dockerfile for the pinned, verified-compliant build
this project's actual CI/Docker path installs before running this suite.
"""

import shutil
import subprocess
from pathlib import Path

import pytest
from volley_worker.ffprobe import (
    FfmpegLicenseViolationError,
    UnsafeMediaFileError,
    compute_sha256,
    probe_video,
    reject_if_reference_style_media,
    verify_ffmpeg_build_is_license_clean,
)

_FFMPEG_AVAILABLE = shutil.which("ffmpeg") is not None and shutil.which("ffprobe") is not None

pytestmark = pytest.mark.skipif(
    not _FFMPEG_AVAILABLE, reason="ffmpeg/ffprobe not found on PATH in this environment"
)


@pytest.fixture(scope="module")
def synthetic_clip(tmp_path_factory) -> Path:
    """A ~2 second, 320x240, 25fps H.264-free (mpeg4) synthetic test clip
    generated entirely from ffmpeg's built-in `testsrc`/`sine` lavfi
    sources -- proves the ingest pipeline's plumbing end-to-end without
    needing (and never trying to obtain) any real video content."""
    out_dir = tmp_path_factory.mktemp("synthetic_clip")
    out_path = out_dir / "clip.mp4"
    subprocess.run(
        [
            "ffmpeg",
            "-f",
            "lavfi",
            "-i",
            "testsrc=duration=2:size=320x240:rate=25",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:duration=2",
            "-c:v",
            "mpeg4",
            "-c:a",
            "aac",
            "-y",
            str(out_path),
        ],
        check=True,
        capture_output=True,
        timeout=60,
    )
    return out_path


def test_probe_video_reads_real_container_metadata(synthetic_clip):
    result = probe_video(synthetic_clip)
    assert result.codec == "mpeg4"
    assert result.duration_seconds is not None
    assert 1.5 < result.duration_seconds < 2.5
    assert result.fps is not None
    assert 24.0 < result.fps < 26.0
    assert result.container_format is not None
    assert "mp4" in result.container_format
    # PTS mapping + dimensions (DATA_FLOW.md's "Video identity" section) --
    # added after independent architecture review found the original
    # ingest pipeline stored none of this, see Video.width's docstring in
    # ontology.py.
    assert result.width == 320
    assert result.height == 240
    assert result.start_time_seconds is not None
    assert result.time_base is not None


def test_compute_sha256_is_deterministic_and_content_addressed(synthetic_clip, tmp_path):
    first = compute_sha256(synthetic_clip)
    second = compute_sha256(synthetic_clip)
    assert first == second
    assert len(first) == 64  # SHA-256 hex digest length

    # A byte-identical copy hashes the same; a modified copy doesn't --
    # this is the actual property the ingest pipeline's dedup detection
    # (services/worker/src/volley_worker/ingest.py) relies on.
    copy_path = tmp_path / "copy.mp4"
    copy_path.write_bytes(synthetic_clip.read_bytes())
    assert compute_sha256(copy_path) == first

    mutated_path = tmp_path / "mutated.mp4"
    mutated_path.write_bytes(synthetic_clip.read_bytes() + b"\x00")
    assert compute_sha256(mutated_path) != first


def test_installed_ffmpeg_build_is_license_clean():
    """Real assertion against whatever ffmpeg/ffprobe is actually on PATH
    right now -- see this file's module docstring for why a failure here,
    on an arbitrary host, is a correct and expected finding, not a bug in
    the check. This is the D-006-required CI verification step, exercised
    directly (also re-run at worker process startup, see celery_app.py,
    and again inside the Docker build itself, see
    infra/docker/python.Dockerfile)."""
    try:
        verify_ffmpeg_build_is_license_clean()
    except FfmpegLicenseViolationError as exc:
        pytest.fail(
            "The ffmpeg/ffprobe build on PATH in this environment is not "
            "license-clean per LICENSE_DECISIONS.md D-006 -- this environment "
            "needs infra/scripts/install-ffmpeg-lgpl.sh's pinned build, not "
            f"whatever is currently installed. Detail: {exc}"
        )


def test_probe_video_refuses_an_hls_playlist_disguised_as_a_video(tmp_path):
    """Regression test for a real, live-demonstrated vulnerability:
    independent security review uploaded a `.m3u8` HLS playlist referencing
    `../../../other-org/video.ts` and got ffprobe to read and report
    metadata for a *different organization's* video entirely, because
    ffmpeg's format auto-detection follows a playlist's own references
    with no awareness of this app's org boundaries. `probe_video` must
    refuse to even attempt probing a text-based reference-style file."""
    playlist = tmp_path / "evil.mp4"  # extension alone doesn't save you -- see below
    playlist.write_text("#EXTM3U\n#EXT-X-VERSION:3\n../other-org/video.ts\n")

    with pytest.raises(UnsafeMediaFileError):
        probe_video(playlist)


def test_probe_video_accepts_a_real_binary_video_file(synthetic_clip):
    """The text-sniff heuristic must not false-positive on real video --
    binary container headers are never printable ASCII, so this should
    pass straight through to ffprobe."""
    reject_if_reference_style_media(synthetic_clip)  # must not raise
