/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Liveness: process is up. No dependency checks -- a slow DB must never
         *     cause an orchestrator to kill and restart a perfectly healthy process.
         */
        get: operations["liveness_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness: dependencies the API actually needs are reachable.
         */
        get: operations["readiness_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Matches */
        get: operations["list_matches_api_v1_matches_get"];
        put?: never;
        /** Create Match */
        post: operations["create_match_api_v1_matches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Match */
        get: operations["get_match_api_v1_matches__match_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Match
         * @description Permanently deletes a match. Every `MatchSet`/`Rally`/.../`Outcome`
         *     row and `ProcessingJob` row cascades at the DB level (all already
         *     `ondelete="CASCADE"` from `matches.id`). Any `Video` linked to this
         *     match only has that link cleared (`ondelete="SET NULL"` on
         *     `Video.match_id`) -- deleting a match never deletes the video footage
         *     itself; use `DELETE /videos/{id}` separately for that.
         */
        delete: operations["delete_match_api_v1_matches__match_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/demo-process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Demo Process */
        post: operations["trigger_demo_process_api_v1_matches__match_id__demo_process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Match Result */
        get: operations["get_match_result_api_v1_matches__match_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sets */
        get: operations["list_sets_api_v1_matches__match_id__sets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/rallies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rallies */
        get: operations["list_rallies_api_v1_matches__match_id__rallies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rallies/{rally_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rally Actions */
        get: operations["list_rally_actions_api_v1_rallies__rally_id__actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rallies/{rally_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rally Analysis
         * @description Return the newest completed, internally consistent analysis bundle.
         *
         *     The result row carries ``organization_id`` specifically so the tenant
         *     boundary is enforced directly in the query. Joining the PipelineRun and
         *     requiring COMPLETED prevents partially published worker output from
         *     becoming visible in replay clients.
         */
        get: operations["get_rally_analysis_api_v1_rallies__rally_id__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Match Statistics
         * @description Computes statistics fresh from the Event Log every call -- per
         *     ONTOLOGY.md, DerivedMetric is never persisted as a mutable number.
         */
        get: operations["get_match_statistics_api_v1_matches__match_id__statistics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/statistics/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stat Evidence
         * @description Return the exact Event Log rows behind one displayed statistic.
         *
         *     This replaces the browser's former one-request-per-rally fan-out with a
         *     single org-scoped query and a canonical server-side predicate shared by
         *     all consumers. The response is deliberately bounded and reports when it
         *     has been truncated.
         */
        get: operations["get_stat_evidence_api_v1_matches__match_id__statistics_evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Videos */
        get: operations["list_videos_api_v1_videos_get"];
        put?: never;
        /** Create Video Upload */
        post: operations["create_video_upload_api_v1_videos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/local-upload/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Local Upload
         * @description The local-dev stand-in for a real signed R2 PUT URL -- see
         *     volley_storage.local.LocalFilesystemStorageAdapter's module docstring.
         *     Never reachable in production (STORAGE_BACKEND=r2 there, so
         *     create_video_upload never issues a URL pointing here, and
         *     Settings._local_storage_cannot_reach_production refuses to even start
         *     with STORAGE_BACKEND=local outside dev/test).
         *
         *     Not a scalability claim for real multi-GB uploads -- production traffic
         *     never hits this route at all: R2's real presigned PUT goes directly
         *     from the browser to R2, per DATA_FLOW.md's "video bytes never transit
         *     FastAPI" rule. This route is the one deliberate, documented exception
         *     to that rule, scoped to local dev only.
         */
        put: operations["local_upload_api_v1_storage_local_upload__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/{video_id}/complete-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Video Upload */
        post: operations["complete_video_upload_api_v1_videos__video_id__complete_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/{video_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Video */
        get: operations["get_video_api_v1_videos__video_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Video
         * @description Permanently deletes a video: every `VideoAsset`/`PipelineRun`/
         *     `ModelRun`/`VideoDetectionFrame` row cascades at the DB level (all
         *     already `ondelete="CASCADE"` from `videos.id` -- see ontology.py), and
         *     every real object this video ever wrote to storage (original + any
         *     proxy/clip assets) is deleted too, not just the DB row -- otherwise the
         *     actual video bytes silently outlive every reference to them. A video
         *     linked to a `Match` only has that link cleared (`ondelete="SET NULL"`)
         *     -- deleting a video never deletes the match it was attached to.
         */
        delete: operations["delete_video_api_v1_videos__video_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/{video_id}/playback-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Video Playback Url
         * @description Issues a short-lived signed GET target for a <video> element's
         *     `src` -- the read-side counterpart of POST /videos' signed upload,
         *     same "bytes never transit FastAPI" rule (DATA_FLOW.md). Requires a
         *     real JWT-authenticated, org-scoped principal (unlike the local-upload/
         *     local-download routes below, which are authorized purely by their own
         *     signed token, matching how a real presigned URL works) -- this route
         *     is what *hands out* that token in the first place, so it's the actual
         *     access-control checkpoint.
         */
        get: operations["get_video_playback_url_api_v1_videos__video_id__playback_url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/{video_id}/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Video Detection
         * @description Enqueues the exploratory RF-DETR detection pipeline (see
         *     volley_worker.detection) for a real uploaded video. Idempotent per the
         *     same rule matches.py's demo-process trigger and complete_video_upload
         *     already use: a QUEUED/RUNNING/COMPLETED run for this video is reused,
         *     never double-enqueued; a FAILED run gets a fresh PipelineRun row (see
         *     PipelineRun's own "one execution" docstring -- unlike ProcessingJob, a
         *     retry here is a new row, not a mutated one). An optional body lets the
         *     caller cap processing to the video's own first `max_duration_seconds`
         *     -- ignored when an existing run is reused below, matching how every
         *     other field of a reused run reflects the *original* trigger, not the
         *     new request. `start_offset_seconds` similarly lets the caller skip a
         *     real match's warmup/pre-play footage and start analysis from the
         *     moment play actually begins (see extract_frames_at_fps's docstring).
         *     `sample_fps` overrides the worker's env-configured detection rate for
         *     this one run.
         */
        post: operations["trigger_video_detection_api_v1_videos__video_id__detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/{video_id}/detection-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Video Detection Status
         * @description Polled by the frontend after POST .../detect. Returns an honest
         *     all-None/zero shape when no detection run has ever been triggered for
         *     this video -- never a fabricated empty result (CLAUDE.md's abstention
         *     principle).
         */
        get: operations["get_video_detection_status_api_v1_videos__video_id__detection_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/{video_id}/detections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Video Detections
         * @description Returns the latest COMPLETED detection run's per-frame boxes, in
         *     frame order. An empty list covers both "never analyzed" and "analysis
         *     still running" -- callers should check detection-status first to tell
         *     those apart, exactly like the video library already treats an empty
         *     `duration_seconds` as "probe pending", not "zero-length video".
         */
        get: operations["list_video_detections_api_v1_videos__video_id__detections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/{video_id}/court-calibration/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Court Calibration
         * @description Debounced live-feedback endpoint for the manual calibration UI --
         *     computes reprojection error for the in-progress keypoint set without
         *     persisting anything, so a human sees calibration quality *while*
         *     clicking, not only after submitting. Calls the exact same ml/court/
         *     geometry functions the real persisting route below does (never a
         *     second, divergent estimator), so the live number and the saved number
         *     can never disagree.
         */
        post: operations["preview_court_calibration_api_v1_videos__video_id__court_calibration_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/{video_id}/court-calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Court Calibration
         * @description Current (non-superseded) calibration for this video, or None if one
         *     has never been created -- an honest empty state, never a fabricated
         *     placeholder, matching get_video_detection_status's own pattern.
         */
        get: operations["get_court_calibration_api_v1_videos__video_id__court_calibration_get"];
        put?: never;
        /**
         * Create Court Calibration
         * @description Manual calibration only (CLAUDE.md: "a correct manual calibration
         *     beats a false automatic one") -- no auto-detection path exists yet.
         *
         *     Creates exactly one CameraSegment per video if none exists yet -- a
         *     deliberate MVP simplification: no shot-boundary/camera-cut detection
         *     pipeline exists, so this assumes one camera framing for the whole
         *     video. Surfaced to the user as a persistent warning in the calibration
         *     UI, never silently assumed away. An existing unsuperseded calibration
         *     on that segment is superseded, never overwritten in place or deleted
         *     -- see CourtCalibration's own docstring on why.
         */
        post: operations["create_court_calibration_api_v1_videos__video_id__court_calibration_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/local-download/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Local Download
         * @description The local-dev stand-in for a real signed R2 GET URL -- the read-side
         *     mirror of local_upload above. Never reachable in production for the
         *     same reasons local_upload isn't (STORAGE_BACKEND=r2 there; a real R2
         *     presigned GET streams the browser <video> element directly from R2,
         *     never through this API).
         *
         *     Authorized purely by the signed `token` (which encodes "download",
         *     distinct from an "upload" token for the same key -- see
         *     LocalFilesystemStorageAdapter._token_for's docstring), not a JWT --
         *     this matches exactly how a real presigned URL works: whoever holds the
         *     URL can fetch it, no separate bearer auth required, for the token's
         *     limited lifetime.
         */
        get: operations["local_download_api_v1_storage_local_download__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionOut */
        ActionOut: {
            /** Id */
            id: string;
            /** Phase Id */
            phase_id: string;
            /** Rally Id */
            rally_id: string;
            /**
             * Action Type
             * @enum {string}
             */
            action_type: "serve" | "reception" | "set" | "attack" | "tip" | "block" | "dig" | "free_ball" | "transition";
            /** Actor Team Id */
            actor_team_id: string;
            /** Actor Roster Id */
            actor_roster_id: string | null;
            /** Video T Start */
            video_t_start: number;
            /** Video T End */
            video_t_end: number;
            /** Court X */
            court_x: number;
            /** Court Y */
            court_y: number;
            /** Confidence */
            confidence: number;
            /**
             * Reviewed Status
             * @enum {string}
             */
            reviewed_status: "unreviewed" | "confirmed" | "corrected";
            /** Quality Rating */
            quality_rating: number | null;
            outcome?: components["schemas"]["OutcomeOut"] | null;
        };
        /**
         * ActionType
         * @enum {string}
         */
        ActionType: "serve" | "reception" | "set" | "attack" | "tip" | "block" | "dig" | "free_ball" | "transition";
        /** AnalysisCalibration */
        AnalysisCalibration: {
            /** Calibration Id */
            calibration_id: string;
            /** Frame Width Px */
            frame_width_px: number;
            /** Frame Height Px */
            frame_height_px: number;
            /** Confidence */
            confidence: number;
            /** Reprojection Error Px */
            reprojection_error_px: number;
            /** Supports Court Plane */
            supports_court_plane: boolean;
            /** Supports Metric 3D */
            supports_metric_3d: boolean;
            /** Camera Count */
            camera_count: number;
        };
        /** AnalysisCapability */
        AnalysisCapability: {
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "estimated" | "abstained" | "unavailable";
            /** Reason */
            reason?: string | null;
        };
        /** AnalysisModelRunRef */
        AnalysisModelRunRef: {
            /** Stage */
            stage: string;
            /** Model Run Id */
            model_run_id: string;
            /** Model Version */
            model_version: string;
            /** Weights Sha256 */
            weights_sha256: string;
            /** Dataset Version */
            dataset_version: string;
        };
        /** AnalysisPoseKeypoint */
        AnalysisPoseKeypoint: {
            /** Name */
            name: string;
            pixel?: components["schemas"]["PixelPoint"] | null;
            world_3d?: components["schemas"]["SpatialEstimate3D"] | null;
            /** Confidence */
            confidence: number;
        };
        /** AnalysisProvenance */
        AnalysisProvenance: {
            /** Organization Id */
            organization_id: string;
            /** Video Id */
            video_id: string;
            /** Video Hash */
            video_hash: string;
            /** Pipeline Run Id */
            pipeline_run_id: string;
            /** Pipeline Version */
            pipeline_version: string;
            /** Config Sha256 */
            config_sha256: string;
            /** Code Commit */
            code_commit: string;
            /** Model Runs */
            model_runs: components["schemas"]["AnalysisModelRunRef"][];
        };
        /** AnalyzedContact */
        AnalyzedContact: {
            /** Contact Id */
            contact_id: string;
            /** Contact Index */
            contact_index: number;
            frame: components["schemas"]["SourceFrameRef"];
            /** Actor Track Id */
            actor_track_id: string;
            /**
             * Team
             * @enum {string}
             */
            team: "home" | "away";
            action_type: components["schemas"]["ActionType"];
            /**
             * Contact Surface
             * @enum {string}
             */
            contact_surface: "left_hand" | "right_hand" | "both_hands" | "forearms" | "head" | "foot" | "other" | "unknown";
            ball_center_pixel: components["schemas"]["PixelPoint"];
            ball_world_3d?: components["schemas"]["SpatialEstimate3D"] | null;
            contact_height: components["schemas"]["ScalarMeasurement"];
            incoming_velocity_mps?: components["schemas"]["Vector3D"] | null;
            outgoing_velocity_mps?: components["schemas"]["Vector3D"] | null;
            target_court_point?: components["schemas"]["SpatialEstimate3D"] | null;
            /** Confidence */
            confidence: number;
        };
        /** AttackStatsOut */
        AttackStatsOut: {
            /** Team Id */
            team_id: string;
            /** Total Attacks */
            total_attacks: number;
            /** Kills */
            kills: number;
            /** Errors */
            errors: number;
            /** Blocked */
            blocked: number;
            /** Efficiency */
            efficiency: number | null;
            /** Zone Counts */
            zone_counts: {
                [key: string]: number;
            };
            /** Takeoff Position Counts */
            takeoff_position_counts: {
                [key: string]: number;
            };
        };
        /**
         * BallDetectionBoxOut
         * @description One ball box within a `VideoDetectionFrameOut`'s `balls` list -- a
         *     single-frame observed pixel position only (RF-DETR's COCO "sports
         *     ball" class), never a trajectory point. Deliberately has no
         *     `temporal_source`/velocity/court-plane fields: those require a working
         *     court-calibration pipeline this project doesn't have yet for real
         *     video (CLAUDE.md's fixed Ball decision -- "never a normal detector
         *     class... never present interpolation as observation"). Any smoothing
         *     between two of these real observed points (e.g. for playback) happens
         *     client-side at render time and is never persisted as a new observation.
         *
         *     `is_static_false_positive` is set by a post-run pass
         *     (volley_worker.ball_filtering) when this exact screen position recurs
         *     across a span of many seconds -- found empirically against real
         *     footage to be the signature of a fixed scene object (a court logo, an
         *     ad board), not the real ball, which is never stationary that long
         *     during active play. Never deletes the underlying detection -- see that
         *     module's docstring for why this stays a flag, not a filter applied
         *     before storage.
         */
        BallDetectionBoxOut: {
            /** Candidate Id */
            candidate_id: string;
            /** Bbox */
            bbox: {
                [key: string]: number;
            };
            /** Confidence */
            confidence: number;
            /**
             * Is Static False Positive
             * @default false
             */
            is_static_false_positive: boolean;
        };
        /** BallPositionSample */
        BallPositionSample: {
            /** T */
            t: number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /**
             * Z
             * @description normalized height, 0 = floor
             */
            z: number;
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "observed" | "interpolated" | "predicted";
            /** Confidence */
            confidence: number;
        };
        /**
         * BallProvenance
         * @enum {string}
         */
        BallProvenance: "observed" | "interpolated" | "predicted";
        /** BallTrajectorySample */
        BallTrajectorySample: {
            frame: components["schemas"]["SourceFrameRef"];
            center_pixel?: components["schemas"]["PixelPoint"] | null;
            world_3d?: components["schemas"]["SpatialEstimate3D"] | null;
            velocity_mps?: components["schemas"]["Vector3D"] | null;
            provenance: components["schemas"]["BallProvenance"];
            /** Confidence */
            confidence: number;
        };
        /** BlockStatsOut */
        BlockStatsOut: {
            /** Team Id */
            team_id: string;
            /** Total Blocks */
            total_blocks: number;
            /** Block Kills */
            block_kills: number;
            /** Block Errors */
            block_errors: number;
        };
        /**
         * BoundingBox
         * @description Normalized (0-1) top-left + width/height -- FiftyOne's own
         *     `Detection.bounding_box` convention, adopted here directly so the
         *     to/from-FiftyOne converters below are a straight field mapping rather
         *     than a coordinate-system translation.
         */
        BoundingBox: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** CourtCalibrationOut */
        CourtCalibrationOut: {
            /** Id */
            id: string;
            /** Camera Segment Id */
            camera_segment_id: string;
            method: components["schemas"]["HomographyMethodOut"];
            /** Image Width */
            image_width: number;
            /** Image Height */
            image_height: number;
            /** Homography Matrix */
            homography_matrix: number[];
            /** Keypoints */
            keypoints: {
                [key: string]: unknown;
            }[] | null;
            /** Net Height M */
            net_height_m: number | null;
            /** Court Width M */
            court_width_m: number;
            /** Court Length M */
            court_length_m: number;
            /** Zone Mirror X */
            zone_mirror_x: boolean | null;
            /** Reprojection Error Px */
            reprojection_error_px: number | null;
            /** Confidence */
            confidence: number | null;
            /** Created By User Id */
            created_by_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CourtCalibrationPreviewRequest
         * @description Body for `POST /videos/{id}/court-calibration/preview` -- the same
         *     keypoint shape as `CreateCourtCalibrationRequest`, minus the fields
         *     that don't affect reprojection error, so a live-typing UI can debounce
         *     a cheap preview call without persisting anything.
         */
        CourtCalibrationPreviewRequest: {
            /** Image Width */
            image_width: number;
            /** Image Height */
            image_height: number;
            /** Keypoints */
            keypoints: components["schemas"]["CourtKeypointIn"][];
        };
        /** CourtCalibrationPreviewResponse */
        CourtCalibrationPreviewResponse: {
            /** Reprojection Error Px */
            reprojection_error_px: number;
        };
        /**
         * CourtKeypointIn
         * @description One clicked (or explicitly marked-occluded) point from the manual
         *     calibration UI. `keypoint_name` must be one of the 10 named
         *     intersections `volley_domain.annotation.COURT_KEYPOINT_NAMES` already
         *     fixes -- see that module and docs/datasets/PROFESSIONAL_ANNOTATION_PROTOCOL.md's
         *     "Court calibration marks" section for the convention this mirrors.
         */
        CourtKeypointIn: {
            /** Keypoint Name */
            keypoint_name: string;
            /** X Pixel */
            x_pixel: number;
            /** Y Pixel */
            y_pixel: number;
            /**
             * Visible
             * @default true
             */
            visible: boolean;
        };
        /**
         * CreateCourtCalibrationRequest
         * @description Body for `POST /videos/{id}/court-calibration`. Manual calibration
         *     only (CLAUDE.md's fixed Court decision: "a correct manual calibration
         *     beats a false automatic one") -- no auto-detection path exists yet.
         *     `image_width`/`image_height` must be the exact native pixel frame the
         *     keypoints were clicked against (a homography fitted on one frame size
         *     is silently wrong by a constant scale factor if applied to another).
         *     `net_height_m` is optional and display-only -- see CourtCalibration's
         *     own docstring for why it is never used to compute ball height/net
         *     clearance.
         */
        CreateCourtCalibrationRequest: {
            /** Image Width */
            image_width: number;
            /** Image Height */
            image_height: number;
            /** Keypoints */
            keypoints: components["schemas"]["CourtKeypointIn"][];
            /** Net Height M */
            net_height_m?: number | null;
            /**
             * Court Width M
             * @default 9
             */
            court_width_m: number;
            /**
             * Court Length M
             * @default 18
             */
            court_length_m: number;
            /** @default main_wide */
            camera_shot_type: components["schemas"]["ShotTypeOut"];
            /** @default usable */
            camera_tactical_usable: components["schemas"]["TacticalUsabilityOut"];
            /** Zone Mirror X */
            zone_mirror_x?: boolean | null;
        };
        /**
         * DetectionBoxOut
         * @description One box within a `VideoDetectionFrameOut`'s `detections` list --
         *     deliberately a small projection of `PlayerTrackPreannotation` (see
         *     volley_domain.preannotation), not the full model: the frontend overlay
         *     only ever needs bbox/confidence/outlier flag, and re-declaring the full
         *     provenance/review-audit shape here would let a client mistake this
         *     exploratory overlay for a reviewable CVAT preannotation, which it is
         *     not (nothing here is queued for human review).
         */
        DetectionBoxOut: {
            /** Candidate Id */
            candidate_id: string;
            /** Bbox */
            bbox: {
                [key: string]: number;
            };
            /** Confidence */
            confidence: number;
            /**
             * Jersey Color Outlier
             * @default false
             */
            jersey_color_outlier: boolean;
        };
        /** DigStatsOut */
        DigStatsOut: {
            /** Team Id */
            team_id: string;
            /** Total Digs */
            total_digs: number;
        };
        /**
         * DownloadTargetOut
         * @description Shape of a signed-download target -- mirrors what a real S3/R2
         *     presigned GET looks like (just a url + expiry; unlike upload there's
         *     no method/headers the client must set, a <video> element's `src` or a
         *     plain `fetch` both just GET the url directly). See
         *     volley_storage.base.DownloadTarget.
         */
        DownloadTargetOut: {
            /** Url */
            url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * FrameRef
         * @description Mirrors DATA_FLOW.md's rule that a frame is never referenced by
         *     frame number alone: both the proxy/source frame index used by the
         *     annotation tool and the normalized analysis timestamp it maps to.
         */
        FrameRef: {
            /** Frame Index */
            frame_index: number;
            /** Timestamp Seconds */
            timestamp_seconds: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HomographyMethodOut
         * @enum {string}
         */
        HomographyMethodOut: "automatic" | "manual" | "hybrid";
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "completed" | "failed";
        /** MatchCreate */
        MatchCreate: {
            /** Home Team */
            home_team: string;
            /** Away Team */
            away_team: string;
            /** Scheduled At */
            scheduled_at?: string | null;
        };
        /** MatchOut */
        MatchOut: {
            /** Id */
            id: string;
            /** Organization Id */
            organization_id: string;
            /** Home Team */
            home_team: string;
            /** Away Team */
            away_team: string;
            /** Home Team Id */
            home_team_id: string | null;
            /** Away Team Id */
            away_team_id: string | null;
            /** Scheduled At */
            scheduled_at: string | null;
            status: components["schemas"]["MatchStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MatchSetOut */
        MatchSetOut: {
            /** Id */
            id: string;
            /** Match Id */
            match_id: string;
            /** Index */
            index: number;
            /** Home Points */
            home_points: number;
            /** Away Points */
            away_points: number;
            /** Winner Team Id */
            winner_team_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MatchStatisticsOut
         * @description Versioned, fully typed public contract for every computed metric.
         *
         *     The pure engine remains the formula source of truth; these models make
         *     shape changes visible in OpenAPI and therefore at TypeScript compile
         *     time instead of failing inside a chart at runtime.
         */
        MatchStatisticsOut: {
            /** Formula Version */
            formula_version: string;
            /** Serve */
            serve: {
                [key: string]: components["schemas"]["ServeStatsOut"];
            };
            /** Reception */
            reception: {
                [key: string]: components["schemas"]["ReceptionStatsOut"];
            };
            /** Attack */
            attack: {
                [key: string]: components["schemas"]["AttackStatsOut"];
            };
            /** Block */
            block: {
                [key: string]: components["schemas"]["BlockStatsOut"];
            };
            /** Dig */
            dig: {
                [key: string]: components["schemas"]["DigStatsOut"];
            };
            /** Sideout Breakpoint */
            sideout_breakpoint: {
                [key: string]: components["schemas"]["SideoutBreakpointStatsOut"];
            };
            /** Setter Distribution */
            setter_distribution: {
                [key: string]: components["schemas"]["SetterDistributionEntryOut"];
            };
            rally_duration: components["schemas"]["RallyDurationStatsOut"];
        };
        /**
         * MatchStatus
         * @enum {string}
         */
        MatchStatus: "draft" | "demo_ready" | "processing" | "completed" | "failed";
        /** OutcomeOut */
        OutcomeOut: {
            /** Id */
            id: string;
            /**
             * Result
             * @enum {string}
             */
            result: "continue" | "point" | "error";
            /** Detail */
            detail: string | null;
        };
        /**
         * PipelineRunStatusOut
         * @enum {string}
         */
        PipelineRunStatusOut: "queued" | "running" | "completed" | "failed";
        /** PixelPoint */
        PixelPoint: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** PlayerPositionSample */
        PlayerPositionSample: {
            /** T */
            t: number;
            /** Player Id */
            player_id: string;
            /**
             * Team
             * @enum {string}
             */
            team: "home" | "away";
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** PlayerStateSample */
        PlayerStateSample: {
            frame: components["schemas"]["SourceFrameRef"];
            /** Track Id */
            track_id: string;
            /** Roster Id */
            roster_id?: string | null;
            /**
             * Team
             * @enum {string}
             */
            team: "home" | "away";
            bbox: components["schemas"]["BoundingBox"];
            court_anchor?: components["schemas"]["SpatialEstimate3D"] | null;
            /** Pose */
            pose?: components["schemas"]["AnalysisPoseKeypoint"][];
            /** Confidence */
            confidence: number;
        };
        /** ProcessingJobOut */
        ProcessingJobOut: {
            /** Id */
            id: string;
            /** Match Id */
            match_id: string;
            /** Task Name */
            task_name: string;
            status: components["schemas"]["JobStatus"];
            /** Progress */
            progress: number;
            /** Stage */
            stage: string | null;
            /** Attempt */
            attempt: number;
            /** Result Data */
            result_data: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RallyAnalysisBundle */
        RallyAnalysisBundle: {
            /**
             * Schema Version
             * @default rally-analysis-v1
             * @constant
             */
            schema_version: "rally-analysis-v1";
            provenance: components["schemas"]["AnalysisProvenance"];
            /** Rally Id */
            rally_id: string;
            /** Set Index */
            set_index: number;
            /** Rally Index In Set */
            rally_index_in_set: number;
            start_frame: components["schemas"]["SourceFrameRef"];
            end_frame: components["schemas"]["SourceFrameRef"];
            calibration: components["schemas"]["AnalysisCalibration"];
            /** Ball Trajectory */
            ball_trajectory: components["schemas"]["BallTrajectorySample"][];
            /** Player States */
            player_states: components["schemas"]["PlayerStateSample"][];
            /** Contacts */
            contacts: components["schemas"]["AnalyzedContact"][];
            /** Biomechanical Metrics */
            biomechanical_metrics?: components["schemas"]["ScalarMeasurement"][];
            /** Capabilities */
            capabilities: {
                [key: string]: components["schemas"]["AnalysisCapability"];
            };
            /** Warnings */
            warnings?: string[];
        };
        /**
         * RallyAnalysisResultOut
         * @description One immutable, completed professional analysis snapshot.
         */
        RallyAnalysisResultOut: {
            /** Id */
            id: string;
            /** Organization Id */
            organization_id: string;
            /** Match Id */
            match_id: string;
            /** Rally Id */
            rally_id: string;
            /** Video Id */
            video_id: string;
            /** Pipeline Run Id */
            pipeline_run_id: string;
            /** Schema Version */
            schema_version: string;
            /** Content Sha256 */
            content_sha256: string;
            bundle: components["schemas"]["RallyAnalysisBundle"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RallyDurationStatsOut */
        RallyDurationStatsOut: {
            /** Count */
            count: number;
            /** Mean Seconds */
            mean_seconds: number | null;
            /** Median Seconds */
            median_seconds: number | null;
            /** Min Seconds */
            min_seconds: number | null;
            /** Max Seconds */
            max_seconds: number | null;
        };
        /** RallyOut */
        RallyOut: {
            /** Id */
            id: string;
            /** Set Id */
            set_id: string;
            /** Index In Set */
            index_in_set: number;
            /** Serving Team Id */
            serving_team_id: string;
            /** Point Winner Team Id */
            point_winner_team_id: string | null;
            /** Video T Start */
            video_t_start: number | null;
            /** Video T End */
            video_t_end: number | null;
            /** Duration Seconds */
            duration_seconds: number | null;
        };
        /** ReceptionStatsOut */
        ReceptionStatsOut: {
            /** Team Id */
            team_id: string;
            /** Total Receptions */
            total_receptions: number;
            /** Rated Receptions */
            rated_receptions: number;
            /** Average Rating */
            average_rating: number | null;
            /** Is Effective */
            is_effective: boolean | null;
        };
        /** RosterPlayer */
        RosterPlayer: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Jersey Number */
            jersey_number: number;
            /**
             * Position
             * @enum {string}
             */
            position: "OH" | "OP" | "MB" | "S" | "L";
        };
        /** ScalarMeasurement */
        ScalarMeasurement: {
            /** Value */
            value?: number | null;
            /** Unit */
            unit: string;
            /**
             * Measurement Mode
             * @enum {string}
             */
            measurement_mode: "image_2d" | "court_plane" | "monocular_physics" | "monocular_size_prior" | "triangulated" | "manual";
            /** Confidence */
            confidence: number;
            /** Uncertainty */
            uncertainty?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "measured" | "estimated" | "abstained";
            /** Abstention Reason */
            abstention_reason?: string | null;
            /** Supporting Frames */
            supporting_frames?: components["schemas"]["FrameRef"][];
        };
        /** ServeStatsOut */
        ServeStatsOut: {
            /** Team Id */
            team_id: string;
            /** Total Serves */
            total_serves: number;
            /** Aces */
            aces: number;
            /** Serve Errors */
            serve_errors: number;
            /** Zone Counts */
            zone_counts: {
                [key: string]: number;
            };
        };
        /** SetterDistributionEntryOut */
        SetterDistributionEntryOut: {
            /** Setter Roster Id */
            setter_roster_id: string;
            /** Total Sets */
            total_sets: number;
            /** Followed By Attack */
            followed_by_attack: number;
            /** Zone Counts */
            zone_counts: {
                [key: string]: number;
            };
        };
        /**
         * ShotTypeOut
         * @enum {string}
         */
        ShotTypeOut: "main_wide" | "endline_wide" | "side_wide" | "closeup" | "replay" | "scoreboard" | "other";
        /** SideoutBreakpointStatsOut */
        SideoutBreakpointStatsOut: {
            /** Team Id */
            team_id: string;
            /** Serve Rallies */
            serve_rallies: number;
            /** Serve Points Won */
            serve_points_won: number;
            /** Breakpoint Pct */
            breakpoint_pct: number | null;
            /** Reception Rallies */
            reception_rallies: number;
            /** Reception Points Won */
            reception_points_won: number;
            /** Sideout Pct */
            sideout_pct: number | null;
        };
        /**
         * SourceFrameRef
         * @description Exact source/proxy mapping; never identifies a frame by index alone.
         */
        SourceFrameRef: {
            /** Source Pts */
            source_pts: number;
            /** Source Time Base */
            source_time_base: string;
            /** Source Timestamp Seconds */
            source_timestamp_seconds: number;
            /** Normalized Timestamp Seconds */
            normalized_timestamp_seconds: number;
            /** Proxy Frame Index */
            proxy_frame_index: number;
        };
        /** SpatialEstimate3D */
        SpatialEstimate3D: {
            point: components["schemas"]["WorldPoint3D"];
            /**
             * Measurement Mode
             * @enum {string}
             */
            measurement_mode: "image_2d" | "court_plane" | "monocular_physics" | "monocular_size_prior" | "triangulated" | "manual";
            /** Confidence */
            confidence: number;
            uncertainty: components["schemas"]["WorldUncertainty"];
            /** Reprojection Error Px */
            reprojection_error_px?: number | null;
            /** Camera Ids */
            camera_ids: string[];
            /** Calibration Id */
            calibration_id: string;
        };
        /**
         * StatCategory
         * @enum {string}
         */
        StatCategory: "serve_total" | "serve_aces" | "serve_errors" | "reception_total" | "attack_total" | "attack_kills" | "attack_errors" | "block_total" | "block_kills" | "dig_total";
        /** StatEvidenceEventOut */
        StatEvidenceEventOut: {
            /** Action Id */
            action_id: string;
            /** Rally Id */
            rally_id: string;
            /** Set Index */
            set_index: number;
            /** Rally Index In Set */
            rally_index_in_set: number;
            /**
             * Action Type
             * @enum {string}
             */
            action_type: "serve" | "reception" | "set" | "attack" | "tip" | "block" | "dig" | "free_ball" | "transition";
            /** Actor Team Id */
            actor_team_id: string;
            /** Video T Start */
            video_t_start: number;
            /** Video T End */
            video_t_end: number;
            /** Court X */
            court_x: number;
            /** Court Y */
            court_y: number;
            /** Quality Rating */
            quality_rating: number | null;
            /** Outcome */
            outcome: ("continue" | "point" | "error") | null;
        };
        /** StatEvidenceOut */
        StatEvidenceOut: {
            /** Formula Version */
            formula_version: string;
            category: components["schemas"]["StatCategory"];
            /** Team Id */
            team_id: string;
            /** Zone */
            zone: (1 | 2 | 3 | 4 | 5 | 6) | null;
            /** Total Events */
            total_events: number;
            /** Returned Events */
            returned_events: number;
            /** Is Truncated */
            is_truncated: boolean;
            /** Events */
            events: components["schemas"]["StatEvidenceEventOut"][];
        };
        /** SyntheticAction */
        SyntheticAction: {
            /** Id */
            id: string;
            /** T Start */
            t_start: number;
            /** T End */
            t_end: number;
            /**
             * Type
             * @enum {string}
             */
            type: "serve" | "reception" | "set" | "attack" | "tip" | "block" | "dig" | "free_ball" | "transition";
            /** Actor Player Id */
            actor_player_id: string;
            /**
             * Actor Team
             * @enum {string}
             */
            actor_team: "home" | "away";
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "continue" | "point" | "error";
            /** Detail */
            detail?: string | null;
            /** Confidence */
            confidence: number;
            /** Court X */
            court_x: number;
            /** Court Y */
            court_y: number;
        };
        /** SyntheticMatch */
        SyntheticMatch: {
            /**
             * Synthetic
             * @default true
             * @constant
             */
            synthetic: true;
            /** Seed */
            seed: number;
            home_roster: components["schemas"]["TeamRoster"];
            away_roster: components["schemas"]["TeamRoster"];
            /** Sets */
            sets: components["schemas"]["SyntheticSet"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** SyntheticRally */
        SyntheticRally: {
            /** Id */
            id: string;
            /** Index In Set */
            index_in_set: number;
            /**
             * Serving Team
             * @enum {string}
             */
            serving_team: "home" | "away";
            /**
             * Point Winner
             * @enum {string}
             */
            point_winner: "home" | "away";
            /** Actions */
            actions: components["schemas"]["SyntheticAction"][];
            /** Player Positions */
            player_positions: components["schemas"]["PlayerPositionSample"][];
            /** Ball Positions */
            ball_positions: components["schemas"]["BallPositionSample"][];
            /** Duration Seconds */
            duration_seconds: number;
            /** Match T Start */
            match_t_start: number;
            /** Match T End */
            match_t_end: number;
        };
        /** SyntheticSet */
        SyntheticSet: {
            /** Index */
            index: number;
            score: components["schemas"]["SyntheticSetScore"];
            /** Rallies */
            rallies: components["schemas"]["SyntheticRally"][];
        };
        /** SyntheticSetScore */
        SyntheticSetScore: {
            /** Home Points */
            home_points: number;
            /** Away Points */
            away_points: number;
            /**
             * Winner
             * @enum {string}
             */
            winner: "home" | "away";
        };
        /**
         * TacticalUsabilityOut
         * @enum {string}
         */
        TacticalUsabilityOut: "usable" | "not_usable" | "partial";
        /** TeamRoster */
        TeamRoster: {
            /** Team Name */
            team_name: string;
            /** Players */
            players: components["schemas"]["RosterPlayer"][];
        };
        /**
         * TriggerDetectionRequest
         * @description Optional body for `POST /videos/{id}/detect`. `start_offset_seconds`
         *     skips the video's own first N seconds -- lets a caller skip real
         *     warmup/pre-play footage and start analysis from the moment play
         *     actually begins. `max_duration_seconds` caps extraction to N seconds
         *     *from that starting point* -- lets a caller deliberately preview/test
         *     against a short prefix instead of committing CPU-only local inference
         *     to the whole remaining runtime up front. `sample_fps` overrides the
         *     worker's env-configured default detection rate for this one run --
         *     lets a caller pay for a much denser ball-motion sample on a short,
         *     deliberately scoped window (paired with the two fields above) without
         *     redeploying the worker for every run.
         */
        TriggerDetectionRequest: {
            /** Max Duration Seconds */
            max_duration_seconds?: number | null;
            /** Start Offset Seconds */
            start_offset_seconds?: number | null;
            /** Sample Fps */
            sample_fps?: number | null;
        };
        /** TriggerDetectionResponse */
        TriggerDetectionResponse: {
            /** Pipeline Run Id */
            pipeline_run_id: string;
            status: components["schemas"]["PipelineRunStatusOut"];
        };
        /**
         * UploadTargetOut
         * @description Shape of a signed-upload target -- mirrors what a real S3/R2
         *     presigned PUT looks like (url + method + headers the client must send)
         *     so the local-dev and production code paths present an identical
         *     contract to the browser. See volley_storage.base.UploadTarget.
         */
        UploadTargetOut: {
            /** Url */
            url: string;
            /**
             * Method
             * @constant
             */
            method: "PUT";
            /** Headers */
            headers: {
                [key: string]: string;
            };
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Vector3D */
        Vector3D: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
        };
        /** VideoDetectionFrameOut */
        VideoDetectionFrameOut: {
            /** Frame Index */
            frame_index: number;
            /** Timestamp Seconds */
            timestamp_seconds: number;
            /** Detections */
            detections: components["schemas"]["DetectionBoxOut"][];
            /** Balls */
            balls: components["schemas"]["BallDetectionBoxOut"][];
        };
        /**
         * VideoDetectionStatusOut
         * @description Polled by the frontend after `POST /videos/{id}/detect`. `status` is
         *     None when no detection run has ever been triggered for this video --
         *     the frontend must render an honest "not analyzed yet" state, never a
         *     fabricated empty result, per CLAUDE.md's abstention principle.
         *
         *     `frames_total` is None until the worker has finished frame extraction
         *     (it needs the real sampled-frame count, not an estimate) -- a client
         *     showing a progress bar should treat "status running, frames_total still
         *     None" as "extracting frames," not divide by zero.
         */
        VideoDetectionStatusOut: {
            /** Pipeline Run Id */
            pipeline_run_id: string | null;
            status: components["schemas"]["PipelineRunStatusOut"] | null;
            /** Model Version */
            model_version: string | null;
            /** Sample Fps */
            sample_fps: number | null;
            /** Frames Detected */
            frames_detected: number;
            /** Frames Total */
            frames_total: number | null;
            /** Error */
            error: string | null;
        };
        /** VideoOut */
        VideoOut: {
            /** Id */
            id: string;
            /** Organization Id */
            organization_id: string;
            /** Match Id */
            match_id: string | null;
            /** Filename */
            filename: string;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Fps */
            fps: number | null;
            /** Codec */
            codec: string | null;
            /** Video Hash */
            video_hash: string | null;
            /** Uploaded By User Id */
            uploaded_by_user_id: string;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            status: components["schemas"]["VideoStatusOut"];
            /** Error */
            error: string | null;
        };
        /** VideoPlaybackResponse */
        VideoPlaybackResponse: {
            /** Video Id */
            video_id: string;
            playback: components["schemas"]["DownloadTargetOut"];
        };
        /**
         * VideoStatusOut
         * @enum {string}
         */
        VideoStatusOut: "uploaded" | "validating" | "ready" | "failed";
        /** VideoUploadRequest */
        VideoUploadRequest: {
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /** Match Id */
            match_id?: string | null;
            /** Size Bytes */
            size_bytes?: number | null;
        };
        /** VideoUploadResponse */
        VideoUploadResponse: {
            /** Video Id */
            video_id: string;
            upload: components["schemas"]["UploadTargetOut"];
        };
        /**
         * WorldPoint3D
         * @description Metric court coordinates.
         *
         *     Origin is the near-left court corner viewed from the calibrated camera:
         *     x runs across the 9 m court, y toward the far baseline over 18 m, and z
         *     points upward. Expanded bounds allow serves and defensive play outside
         *     the lines while rejecting unit/axis mistakes early.
         */
        WorldPoint3D: {
            /** X M */
            x_m: number;
            /** Y M */
            y_m: number;
            /** Z M */
            z_m: number;
        };
        /** WorldUncertainty */
        WorldUncertainty: {
            /** X Std M */
            x_std_m: number;
            /** Y Std M */
            y_std_m: number;
            /** Z Std M */
            z_std_m: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    readiness_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_matches_api_v1_matches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"][];
                };
            };
        };
    };
    create_match_api_v1_matches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_api_v1_matches__match_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_match_api_v1_matches__match_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_demo_process_api_v1_matches__match_id__demo_process_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_result_api_v1_matches__match_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyntheticMatch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sets_api_v1_matches__match_id__sets_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchSetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rallies_api_v1_matches__match_id__rallies_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RallyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rally_actions_api_v1_rallies__rally_id__actions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rally_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rally_analysis_api_v1_rallies__rally_id__analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rally_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RallyAnalysisResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_statistics_api_v1_matches__match_id__statistics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchStatisticsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stat_evidence_api_v1_matches__match_id__statistics_evidence_get: {
        parameters: {
            query: {
                category: components["schemas"]["StatCategory"];
                team_id: string;
                zone?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatEvidenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_videos_api_v1_videos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoOut"][];
                };
            };
        };
    };
    create_video_upload_api_v1_videos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VideoUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    local_upload_api_v1_storage_local_upload__key__put: {
        parameters: {
            query: {
                token: string;
                expires_at: string;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_video_upload_api_v1_videos__video_id__complete_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_api_v1_videos__video_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_video_api_v1_videos__video_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_playback_url_api_v1_videos__video_id__playback_url_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoPlaybackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_video_detection_api_v1_videos__video_id__detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TriggerDetectionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerDetectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_detection_status_api_v1_videos__video_id__detection_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoDetectionStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_video_detections_api_v1_videos__video_id__detections_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoDetectionFrameOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_court_calibration_api_v1_videos__video_id__court_calibration_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourtCalibrationPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourtCalibrationPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_court_calibration_api_v1_videos__video_id__court_calibration_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourtCalibrationOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_court_calibration_api_v1_videos__video_id__court_calibration_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCourtCalibrationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourtCalibrationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    local_download_api_v1_storage_local_download__key__get: {
        parameters: {
            query: {
                token: string;
                expires_at: string;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
