"""initial: matches and processing_jobs

Revision ID: 0001
Revises:
Create Date: 2026-08-28

Hand-written (not autogenerated) -- see PROJECT_STATUS.md: this session's
sandbox had no live Postgres available to run `alembic revision
--autogenerate` against. The schema below is a direct, verified transcription
of volley_domain.models as of this revision; run `alembic check` against a
real Postgres before the next migration to confirm there's no drift.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "matches",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("organization_id", sa.String(length=255), nullable=False),
        sa.Column("home_team", sa.String(length=255), nullable=False),
        sa.Column("away_team", sa.String(length=255), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_by_user_id", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index("ix_matches_organization_id", "matches", ["organization_id"])

    op.create_table(
        "processing_jobs",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column(
            "match_id",
            sa.String(length=36),
            sa.ForeignKey("matches.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.String(length=255), nullable=False),
        sa.Column("task_name", sa.String(length=100), nullable=False),
        sa.Column("dedup_key", sa.String(length=255), nullable=False),
        sa.Column("celery_task_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=100), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("result_data", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.UniqueConstraint("dedup_key", name="uq_processing_jobs_dedup_key"),
    )
    op.create_index("ix_processing_jobs_match_id", "processing_jobs", ["match_id"])
    op.create_index("ix_processing_jobs_organization_id", "processing_jobs", ["organization_id"])


def downgrade() -> None:
    op.drop_index("ix_processing_jobs_organization_id", table_name="processing_jobs")
    op.drop_index("ix_processing_jobs_match_id", table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_index("ix_matches_organization_id", table_name="matches")
    op.drop_table("matches")
